---
name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  terraform:
    name: Terraform CI/CD
    uses: melorga-portfolio/gha-workflows/.github/workflows/terraform.yml@main
    with:
      terraform_version: '1.8.5'
      working_directory: './infrastructure'
      environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
      auto_apply: false  # Manual approval for EKS clusters
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

  kubernetes-lint:
    name: Kubernetes Manifests Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Lint Kubernetes manifests
        uses: azure/k8s-lint@v1
        with:
          manifests: |
            kubernetes/namespaces/*.yaml
            kubernetes/applications/*.yaml
            kubernetes/monitoring/*.yaml

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
      
      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
